config/routes.rb
Rails.application.routes.draw do

  root 'home#index'
  #root 'home#construction'
  #get 'home', :to => 'home#index'
  get 'stylist_home/index'

  get 'alog', :to => 'admin_access#menu'
  get 'admin_access/login'
  get 'admin_access/menu'
  post 'admin_access/attempt_login'
  get 'admin_access/logout'


  get 'client_access/login'
  get 'client_access/menu'
  post 'client_access/attempt_login'
  get 'client_access/logout'
  get 'client_access/forgot'
  post 'client_access/reset'
  get 'client_access/password_form'
  post 'client_access/update_password'


  get 'stylist_access/stylist_login'
  get 'stylist_access/stylist_menu'
  post 'stylist_access/stylist_attempt_login'
  get 'stylist_access/stylist_logout'
  get 'stylist_access/forgot'
  post 'stylist_access/reset'
  get 'stylist_access/password_form'
  post 'stylist_access/update_password'

    resources :stylists do
        member do
          get :delete
          get :new_stylist_rating
          post :create_stylist_rating
          get :new_portfolio
          post :create_portfolio
          get :edit_offering
          patch :update_offering
        end
      end

      resources :clients do
        member do
          get :delete
          get :show_style
          post :create_fav_styles
          delete :destroy_fav_styles
          post :create_fav_stylists
          delete :destroy_fav_stylists
        end

        collection do
          get :index_styles
        end
      end

      resources :ratings do
        member do
          get :delete
          get :show_admin
        end
      end

      resources :styles do
        member do
          get :delete
        end
      end

      resources :portfolios do
        member do
          get :delete
          get :show_client
          get :show_stylist
          get :show_admin
        end
      end

      resources :admins do
        member do
          get :delete
          get :show_rating
          get :edit_rating
          patch :update_rating
          get :delete_rating
          delete :destroy_rating
          get :show_portfolio
          get :edit_portfolio
          patch :update_portfolio
          get :delete_portfolio
          delete :destroy_portfolio

        end
        collection do
          get :index_ratings
          get :index_portfolios
        end
      end


      resources :hairstyles do
        member do
          get :delete
        end
      end

      resources :hairstyle_offerings do
        member do
          get :delete
        end
      end

      resources :hairstyle_requests do
        member do
          get :delete
        end
      end

      resources :hairstyle_matches do
        member do
          get :delete
        end
      end



      resources :cities do
          member do
            get :delete
          end

          collection do
            post :create_all
          end
        end


      resources :areas do
        member do
          get :delete
        end

        collection do
          get :remove_all
        end
      end

      resources :contact_forms do
        member do
          get :delete
        end
      end

      resources :blogs do
        member do
          get :delete
        end
      end

      resources :conversations, only: [:index, :show]
      resources :personal_messages, only: [:new, :create]
      resources :users, only: [:index]

      resources :requests
      resources :responses

end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

app/models/conversation.rb
class Conversation < ApplicationRecord

  belongs_to :author, class_name: "User"
  belongs_to :receiver, class_name: "User"
  has_many :personal_messages, -> {order(created_at: :asc)}, dependent: :destroy

  scope :participating, lambda {|user| where("(conversations.author_id = ? OR conversations.receiver_id = ?)", user.id, user.id)}
  scope :between, lambda {|sender_id, receiver_id| where(author_id: sender_id, receiver_id: receiver_id).or(where(author_id: receiver_id, receiver_id: sender_id)).limit(1)}

  validates :author, uniqueness: {scope: :receiver}

  def with(user)
    author == user ? receiver : author
  end

  def participates?(user)
    author == user || receiver == user
  end

end

app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController

  before_action :set_conversation, except: [:index]
  before_action :check_participating!, except: [:index]

  def index
    @conversations = Conversation.participating(current_user.user).order('updated_at DESC')
  end

  def show
    @personal_message = PersonalMessage.new
  end

  private

  def set_conversation
    @conversation = Conversation.find_by(id: params[:id])
  end

  def check_participating!
    redirect_to(conversations_path) unless @conversation && @conversation.participates?(current_user.user)
  end

end

app/helpers/conversations_helper.rb
module ConversationsHelper
end

app/views/conversations/_conversation.html.erb
<div>
    <p>Chatting with: <strong><%= conversation.with(current_user.user).operator.username %></strong></p>

    <em>- <%= conversation.personal_messages.last.body.truncate(50) %>....</em>
    <br>

    <span><%= link_to("View Messages", conversation_path(conversation))%></span>
    <hr>
</div>

app/views/conversations/create.html.erb
<h1>Conversations#create</h1>
<p>Find me in app/views/conversations/create.html.erb</p>

app/views/conversations/index.html.erb
<div class = "container">

  <% if current_user.has_role? :def_client %>
    <%= link_to("<< Back to Profile", client_path(current_user), class: "btn btn-sm mt-2")%>
  <% else current_user.has_role? :def_stylist %>
    <%= link_to("<< Back to Profile", stylist_path(current_user), class: "btn btn-sm mt-2")%>
  <% end %>

  <div id = "conversations-body">
    <h2 class = "text-center">Inbox</h2>
    <hr><hr>
    <%= render @conversations %>
  </div>
</div>

app/views/conversations/show.html.erb
<div class = "container">
  <%= link_to("Inbox", conversations_path, class: ' btn btn-sm m-2')%>
  <h3>Chatting with: <%= @conversation.with(current_user.user).operator.username %></h3>

  <div id = "conversation-main">
    <div id = "conversation-body">

      <%= render @conversation.personal_messages %>

    </div><!-- conversation-body -->
    <div>
    <%= form_for @personal_message do |f| %>
      <%= hidden_field_tag "conversation_id", @conversation.id %>
      <div class = "form-group">
        <%= f.text_area :body, class: "form-control" %>
      </div>

      <div class = "text-center">
        <%= f.submit "Send", class: "btn btn-md" %>
      </div>
    <% end %>
  </div><!-- form-group -->
  </div><!-- conversation-main -->

</div><!-- container -->