config/routes.rb
Rails.application.routes.draw do

  root 'home#index'
  #root 'home#construction'
  #get 'home', :to => 'home#index'
  get 'stylist_home/index'

  get 'alog', :to => 'admin_access#menu'
  get 'admin_access/login'
  get 'admin_access/menu'
  post 'admin_access/attempt_login'
  get 'admin_access/logout'


  get 'client_access/login'
  get 'client_access/menu'
  post 'client_access/attempt_login'
  get 'client_access/logout'
  get 'client_access/forgot'
  post 'client_access/reset'
  get 'client_access/password_form'
  post 'client_access/update_password'


  get 'stylist_access/stylist_login'
  get 'stylist_access/stylist_menu'
  post 'stylist_access/stylist_attempt_login'
  get 'stylist_access/stylist_logout'
  get 'stylist_access/forgot'
  post 'stylist_access/reset'
  get 'stylist_access/password_form'
  post 'stylist_access/update_password'

    resources :stylists do
        member do
          get :delete
          get :new_stylist_rating
          post :create_stylist_rating
          get :new_portfolio
          post :create_portfolio
          get :edit_offering
          patch :update_offering
        end
      end

      resources :clients do
        member do
          get :delete
          get :show_style
          post :create_fav_styles
          delete :destroy_fav_styles
          post :create_fav_stylists
          delete :destroy_fav_stylists
        end

        collection do
          get :index_styles
        end
      end

      resources :ratings do
        member do
          get :delete
          get :show_admin
        end
      end

      resources :styles do
        member do
          get :delete
        end
      end

      resources :portfolios do
        member do
          get :delete
          get :show_client
          get :show_stylist
          get :show_admin
        end
      end

      resources :admins do
        member do
          get :delete
          get :show_rating
          get :edit_rating
          patch :update_rating
          get :delete_rating
          delete :destroy_rating
          get :show_portfolio
          get :edit_portfolio
          patch :update_portfolio
          get :delete_portfolio
          delete :destroy_portfolio

        end
        collection do
          get :index_ratings
          get :index_portfolios
        end
      end


      resources :hairstyles do
        member do
          get :delete
        end
      end

      resources :hairstyle_offerings do
        member do
          get :delete
        end
      end

      resources :hairstyle_requests do
        member do
          get :delete
        end
      end

      resources :hairstyle_matches do
        member do
          get :delete
        end
      end



      resources :cities do
          member do
            get :delete
          end

          collection do
            post :create_all
          end
        end


      resources :areas do
        member do
          get :delete
        end

        collection do
          get :remove_all
        end
      end

      resources :contact_forms do
        member do
          get :delete
        end
      end

      resources :blogs do
        member do
          get :delete
        end
      end

      resources :conversations, only: [:index, :show]
      resources :personal_messages, only: [:new, :create]
      resources :users, only: [:index]

      resources :requests
      resources :responses

end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

app/controllers/home_controller.rb
class HomeController < ApplicationController

  layout :resolve_layout

  def index
  end

  def construction
  end

private

  def resolve_layout

    case action_name
      when 'index'
        'application'
      when 'construction'
        'construction'
      end
  end


end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_client_current.html.erb
<section class="background_home_three text-center">
          <div>
                <h2>CLIENT SITE LAUNCH: <span style = "text-decoration:underline;">Coming Soon</span></h2>

                  <h4 class = "m-4">Keep up to date with the developments and be one of the first clients to use Hairlinkd</h4>
                    <%= button_to("SIGN UP NOW!", new_client_path, class: "btn btn-gold", id: "client_register_div_two", style: "display: inline-block;", :method => :get) %>
          </div>
</section>

app/views/home/_client_div_four.html.erb
<section id = "background_home_four">
        <div class="text-center" style = "padding-top:150px; padding-bottom:150px;">
          <h1 style = "color:#EAEAEA; padding:10px;">Now you can look good and feel great all the time</h1>
        </div>
</section>

app/views/home/_client_div_one.html.erb
<div class = "container">
  <div class = "row d-flex align-items-center" style = "margin:30px 0px 30px;">

    <sub-section class = "col col-md-6">

        <div>
          <div class="text-center m-4">
            <h1>GET <span style = "color:#D4AF37;">LINKD</span> UP</h1>
          </div>

          <div class="lead" style = "text-align:justify;">
            <p>Looking good really does not have to be a struggle.</p>
            <p>Our goal is to find the best possible hair stylist to suite your hairstyle requirements.</p>
            <strong><p>So, whether you are new in the area, or you have this amazing hair style in mind, we are here to point you in the right direction.</p></strong>
          </div>


            <div class = "text-center">
              <%= button_to "Sign up as a Client", new_client_path, class: "btn", id: "client_register_div_one", style: "display: inline-block;",:method => :get %>

            </div>



        </div>
    </sub-section>

  <sub-section class = "col col-md-6">
      <img src="/assets/background/client1.jpg" class = "m-2" style = "box-shadow: 10px 10px 10px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);" />
  </sub-section>

</div>  <!-- container -->

app/views/home/_client_div_three.html.erb
<div class = "container">
  <div class = "row d-flex align-items-center" style = "margin:30px 0px 30px;">

  <sub-section class = "col col-md-6;">
      <img src="/assets/background/connect_client1.jpg" class = "img pt-5 pb-5" />
  </sub-section>

    <sub-section class = " col col-md-6" style = "height:100%;">

        <div>
          <div class="text-center m-4">
            <h1>HOW WE GET YOU <span style = "color:#D4AF37;">LINKD</span></h1>
          </div>

          <div class="lead" style = "text-align:justify;">
            <p>We make the effort to get to know <strong>you and your exact needs.</strong></p>
            <p>Our matching algorithm then searches through thousands of stylists to find you the best possible stylists for your needs.</p>
               Our algorithm will search using two factors:
               <ul>
                 <li>first, the best possible stylist that can cater for your needs (e.g. style, products on stock, location, budget etc) and</li>
                 <li>second, the best possible stylist that will offer the best experience while doing your hair</li>
               </ul>
.
          </div>

          <div class = "text-center">
            <%= button_to "Sign up as a Client", new_client_path, class: "btn", id: "client_register_div_one", style: "display: inline-block;",:method => :get %>

          </div>

        </div>
    </sub-section>

  </div>  <!-- row -->
</div>  <!-- container -->

app/views/home/_client_div_two.html.erb
<section id = "background_home_two">
        <div class="container" style = "margin-top:100px; margin-bottom:100px;">
          <blockquote class = "blockquote">
            <h3 style = "color:#EAEAEA;">I love my hair because it’s a reflection of my soul. It’s dense, it’s kinky, it’s soft, it’s textured, it’s difficult, it’s easy and it’s fun. That’s why I love my hair.</h3>
            <footer class = "blocquote-footer" style = "color:#D4AF37;">-Tracee Ellis Ross</footer>
          </blockquote>

          </div>
</section>

app/views/home/_contact.html.erb
<section>
  <div class = "container text-center p-5 lead">
    <div style ='width:100%; padding:10px;'>
      <h2>Lets Keep In Touch</h2>
    </div>


    <div style = "font-size:1.4em">
          <p>We would love to here from you.</p>
          <p>Whether its an issue you have, or you just want to say hello!!</p>
          <p>Drop us a message and we'll come back to you</p>
          <%= button_to("Contact Us", new_contact_form_path, method: :get, class: "btn")%>
    </div>

    <div class = "row d-flex justify-content-center mt-5">

      <div class="m-2">
        <%= link_to (image_tag asset_path 'web-deco/facebook_icon1.jpg'), "https://www.facebook.com/hairlinkd/", :target => "_blank" %>
      </div>

      <div class="m-2">
        <%= image_tag asset_path 'web-deco/twitter_icon1.jpg' %>
      </div>

      <div class="m-2">
        <%= image_tag asset_path 'web-deco/insta_icon1.jpg' %>
      </div>

    </div>

  </div>
  </section>

app/views/home/_intro_div.html.erb
<div class="#">
  <section id = "background_home_one">


        <div class="container">
          <div class = "row">
              <div class="col-sm-9 offset-md-3">
                <div class="jumbotron jumbotron-fluid" id = "jumbo_1">
                  <div id = "jumbo_1_text lead">
                    <h2>With thousands of hair stylists out there, are you really sure you have found your one?</h2>
                  </div>
                </div>
              </div>
          </div>
        </div>


  </section>
</div>

app/views/home/_stylist.html.erb
 <div class = 'card-body'>
   <div class = 'card' >

     <div class="img-thumbnail rounded card-img">
       <%= image_tag stylist.avatar.url(:thumb).to_s, :style => "width:150px;"%>
     </div>

     <p class = 'card-text' style = 'color:black;'>
       <strong><%= stylist.username %></strong> </br>

       <strong>City:</strong>
        <% stylist.cities.each do |c|%>
        <%= c.city %>
        <% end %>
      </br>

      <strong> Rating:</strong> <%=  stylist.overall_rating %> (<%= pluralize(stylist.ratings.count, 'Review') %>)
     </p>

    <div class = 'card-footer'>
       <%= link_to("", stylist_path(stylist))%><br>
    </div> <!--card-footer-->

   </div> <!--card-->
   </div><!--card body-->

app/views/home/_stylist_current.html.erb
<section class="background_home_three text-center">

          <div class = "mt-4">
            <h3>LATEST STYLISTS TO SIGN UP</h3>
            <h3><i class = "glyphicon glyphicon-download"></i></h3>
          </div>

          <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
            <ol class="carousel-indicators">
              <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
              <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
              <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
            </ol>

            <div class="carousel-inner">

              <% @last_stylist.each do |stylist| %>
                <div class="carousel-item <%= 'active' if stylist == @last_stylist[0] %>">
                  <%= render(:partial => 'stylist', :html => {:multiport => true}, :locals => {:stylist => stylist}) %>
                </div>
                <% end %>

            <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
              <span class="carousel-control-prev-icon" aria-hidden="true" style= "text-color:black;"></span>
              <span class="sr-only">Previous</span>
            </a>
            <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
              <span class="carousel-control-next-icon" aria-hidden="true"></span>
              <span class="sr-only">Next</span>
            </a>
        </div>
        </div>

        <div class = "mt-3">
          <h2>FREE FOR FIRST 100 STYLISTS!!!</h2>
            <h4 style = 'margin-bottom:20px;'>Registered Stylists: <%= @stylist_count %></h4>
          <%= button_to("SIGN UP AS A STYLIST!!", new_stylist_path, class: "btn btn-gold", id: "client_register_div_two", style: "display: inline-block;", :method => :get) %>
        </div>
</section>

app/views/home/_stylist_div.html.erb
<section class="">
  <div class = "container">
    <div class = "row">

      <sub-section class = " col col-md-6 text-center" style = "font-size:1.4em;">
            <div class = "m-3">
              <img src="/assets/web-deco/Icon-1.png" />
            </div>

            <div>
              <h2 style = 'text-decoration:underline; margin-bottom:15px;'>Hairlinkd for Stylists</h2>
              <p>Connect with clients who are looking for your skills <p><hr>
              <p>Showcase your skills and standout from the rest<p><hr>
              <p>Build credibility and a strong following<p><hr>
              <p>Gain popularity through reviews<p><hr>
              <p>Grow your customer base<p><hr>


            </div>

            <div>
              <p><strong>Check it Out Now</strong></p>
              <%= button_to("Register as a Stylist", new_stylist_path, class: "btn btn-lg", id: "client_register_div_two", style: "display: inline-block;", :method => :get) %>
            </div>
        </sub-section>

        <sub-section class = "col col-md-6">
            <img src="/assets/background/client.jpg" class = "img img-fluid" />
        </sub-section>
      </div>  <!-- row -->
    </div>  <!-- container -->
  </section>

app/views/home/_stylist_intro.html.erb
<div class = "container">
    <div class="jumbotron">
      <h1 class="display-4">Hair Stylists</h1>
      <h2 class="lead display-5">Think skill is all you need to keep your clients happy? Find out how we can help you and your business grow.</h2>
      <hr class="my-4">

      <div class="text-center">
        <h4 style = "padding-bottom:20px;">Check out the Stylist's Page.</h4>
          <%= button_to "THE STYLIST'S PAGE", stylist_home_index_path, class: "btn btn-block", id: "stylist_page_button", style: "color:gold; font-weight:bold;", :method => :get %>
      </div>

    </div>
</div>  <!-- container -->

app/views/home/_top_3.html.erb
<div class = "card-body carousel slide" id ="top_3" data-ride = "carousel">

  <h4 class = "card-title">Top Trending Stylists</h4>
    <div class = "carousel-inner">

      <div class = "carousel-item active">
        <div class = 'card-header'>
          <h5 class = 'card-title'><%= @stylist.first.name %></h5>
        </div>

        <div class="img-thumbnail rounded card-img">
          <%= image_tag @stylist.first.avatar.url(:thumb).to_s %>
        </div>

        <p class = 'card-text'> <strong> Rating:</strong> <%=  @stylist.first.overall_rating %> (<%= pluralize(@stylist.first.ratings.count, 'Reviews') %>) <br />
         <strong>City:</strong> <%= "#" %> </p>
      </div>

      <div class = "carousel-item">
        <div class = 'card-header'>
          <h5 class = 'card-title'><%= @stylist.second.name %></h5>
        </div>

        <div class="img-thumbnail rounded card-img">
          <%= image_tag @stylist.second.avatar.url(:thumb).to_s %>
        </div>

        <p class = 'card-text'> <strong> Rating:</strong> <%=  @stylist.second.overall_rating %> (<%= pluralize(@stylist.first.ratings.count, 'Reviews') %>) <br />
         <strong>City:</strong> <%= @stylist.second.city %> </p>
      </div>

      <div class = "carousel-item">
        <div class = 'card-header'>
          <h5 class = 'card-title'><%= @stylist.third.name %></h5>
        </div>

        <div class="img-thumbnail rounded card-img">
          <%= image_tag @stylist.third.avatar.url(:thumb).to_s %>
        </div>

        <p class = 'card-text'> <strong> Rating:</strong> <%=  @stylist.third.overall_rating %> (<%= pluralize(@stylist.third.ratings.count, 'Reviews') %>) <br />
         <strong>City:</strong> <%= @stylist.third.city %> </p>
      </div>

    </div><!--carousel-inner-->

    <a class = "carousel-control-prev" href = "#top_3" role = "button" data-slide = "prev">
      <span class = "badge badge-primary badge-pill bg-dark">
        <span class = "carousel-control-prev-icon" style "text-color:black;" aria-hidden = "true">
          <span class = "sr-only">Previous</span>
        </span>
      </span>
    </a>

    <a class = "carousel-control-next" href = "#top_3" role = "button" data-slide = "next">
      <span class = "badge badge-primary badge-pill bg-dark">
        <span class = "carousel-control-next-icon" style "text-color:black;" aria-hidden = "true">
          <span class = "sr-only">Next</span>
        </span>
      </span>
    </a>

    <p>Log in to check it out</p>
    <button type="button" class = "btn btn-secondary">Log In</button>

</div><!--card-body-->

app/views/home/index.html.erb
<!-- All HTML for the front page comes here-->

<%= render(:partial => 'intro_div') %>

<%= render(:partial => 'client_div_one') %>

<%= render(:partial => 'stylist_intro') %>

<%= render(:partial => 'client_div_two') %>

<%= render(:partial => 'client_div_three') %>

<%= render(:partial => 'client_div_four') %>

<%= render(:partial => 'contact') %>



<footer>
  <div class = "text-center mt-5" style = "background-color:black; color:white;">
    &copy; 2019 Hairlinkd (Pty) Ltd. All Rights Reserved. <span><img style='width:25px;' src = "/assets/web-deco/SA_flag.png"/></span>
  </div>
</footer>