config/routes.rb
Rails.application.routes.draw do

  root 'home#index'
  #root 'home#construction'
  #get 'home', :to => 'home#index'
  get 'stylist_home/index'

  get 'alog', :to => 'admin_access#menu'
  get 'admin_access/login'
  get 'admin_access/menu'
  post 'admin_access/attempt_login'
  get 'admin_access/logout'


  get 'client_access/login'
  get 'client_access/menu'
  post 'client_access/attempt_login'
  get 'client_access/logout'
  get 'client_access/forgot'
  post 'client_access/reset'
  get 'client_access/password_form'
  post 'client_access/update_password'


  get 'stylist_access/stylist_login'
  get 'stylist_access/stylist_menu'
  post 'stylist_access/stylist_attempt_login'
  get 'stylist_access/stylist_logout'
  get 'stylist_access/forgot'
  post 'stylist_access/reset'
  get 'stylist_access/password_form'
  post 'stylist_access/update_password'

    resources :stylists do
        member do
          get :delete
          get :new_stylist_rating
          post :create_stylist_rating
          get :new_portfolio
          post :create_portfolio
          get :edit_offering
          patch :update_offering
        end
      end

      resources :clients do
        member do
          get :delete
          get :show_style
          post :create_fav_styles
          delete :destroy_fav_styles
          post :create_fav_stylists
          delete :destroy_fav_stylists
        end

        collection do
          get :index_styles
        end
      end

      resources :ratings do
        member do
          get :delete
          get :show_admin
        end
      end

      resources :styles do
        member do
          get :delete
        end
      end

      resources :portfolios do
        member do
          get :delete
          get :show_client
          get :show_stylist
          get :show_admin
        end
      end

      resources :admins do
        member do
          get :delete
          get :show_rating
          get :edit_rating
          patch :update_rating
          get :delete_rating
          delete :destroy_rating
          get :show_portfolio
          get :edit_portfolio
          patch :update_portfolio
          get :delete_portfolio
          delete :destroy_portfolio

        end
        collection do
          get :index_ratings
          get :index_portfolios
        end
      end


      resources :hairstyles do
        member do
          get :delete
        end
      end

      resources :hairstyle_offerings do
        member do
          get :delete
        end
      end

      resources :hairstyle_requests do
        member do
          get :delete
        end
      end

      resources :hairstyle_matches do
        member do
          get :delete
        end
      end



      resources :cities do
          member do
            get :delete
          end

          collection do
            post :create_all
          end
        end


      resources :areas do
        member do
          get :delete
        end

        collection do
          get :remove_all
        end
      end

      resources :contact_forms do
        member do
          get :delete
        end
      end

      resources :blogs do
        member do
          get :delete
        end
      end

      resources :conversations, only: [:index, :show]
      resources :personal_messages, only: [:new, :create]
      resources :users, only: [:index]

      resources :requests
      resources :responses

end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

app/models/rating.rb
class Rating < ApplicationRecord

  belongs_to :client
  belongs_to :stylist


  #validates_presence_of :Comment
  validate :today_or_before
  validate :date_too_far
  validate :rating_1_missing
  validate :rating_2_missing
  validate :rating_3_missing
  validate :rating_4_missing
  validate :rating_5_missing

  private

  def today_or_before
    if date_of_appointment >= 1.day.from_now
      errors.add(:date_of_appointment, "can't be after today")
    end
  end

  def date_too_far
    if date_of_appointment < 1.month.ago
      errors.add(:date_of_appointment, "can't be a more than a month ago")
    end
  end

  def rating_1_missing
    if rating_1 == 0.0
      errors.add(:base, "First rating incomplete")
    end
  end

  def rating_2_missing
    if rating_2 == 0.0
      errors.add(:base, "Second rating incomplete")
    end
  end

  def rating_3_missing
    if rating_3 == 0.0
      errors.add(:base, "Third rating incomplete")
    end
  end

  def rating_4_missing
    if rating_4 == 0.0
      errors.add(:base, "Fourth rating incomplete")
    end
  end

  def rating_5_missing
    if rating_5 == 0.0
      errors.add(:base, "Fifth rating incomplete")
    end
  end


end

app/controllers/ratings_controller.rb
class RatingsController < ApplicationController

  layout 'application'

  before_action :get_tables, :only => [:new, :create, :edit, :update]


  #after_action :get_overall_rating, :only => [:new, :create, :edit, :update]

    def index
      @rating = Rating.all
      # This is where the list of all the ratings of the stylists will be controlled
    end

    def show
      @rating = Rating.find(params[:id])
      @stylist = Stylist.find(@rating.stylist_id)
      @client = Client.find(@rating.client_id)

    end

    def show_client
      @rating = Rating.find(params[:id])
      @stylist = @rating.stylist_id
      @client = @rating.client_id
    end

    def show_stylist
      @rating = Rating.find(params[:id])
      @client = @rating.client_id
    end

    def show_admin
      @rating = Rating.find(params[:id])
      @stylist = @rating.stylist_id
      @client = @rating.client_id
    end

    def new
      @stylist = Stylist.find(params[:stylist_id])
      @rating = Rating.new(:client_id => current_user.id, :stylist_id => @stylist.id)
    end

    def create
      #creating of new rating of the particular stylist

      @rating = Rating.new(rating_params)

        if @rating.save

          get_average_rating
          add_to_overall_rating

          flash[:notice] = "Rating successful"
          redirect_to (rating_path(@rating, :stylist_id => @rate.stylist.id))
        else
          render ('new')
        end
    end

    def edit
      @rating = Rating.find(params[:id])
    end

    def update
      @rating = Rating.find(params[:id])

        if  @rating.update_attributes(rating_params)
          get_average_rating
          update_overall_rating
          flash[:notice] = "Rating Updated Successfully"
          redirect_to(rating_path(@rating, :stylist_id => @hstylist.id))
        else
          flash[:notice] = "Oops!! Something went wrong, please try again"
          render 'edit'
        end
    end

    def delete
      @rating = Rating.find(params[:id])
    end

    def destroy
      @rating = Rating.find(params[:id])
      @rating.destroy
      update_overall_rating
      flash[:notice] = "Your Rating Has Been Deleted"
      redirect_to (index_stylists_clients_path(current_user.id))
    end

  private
    def rating_params
      params.require(:rating).permit(:stylist_id, :client_id, :date_of_appointment, :style_id, :rating_1, :rating_2, :rating_3, :rating_4, :rating_5, :total_rating, :return, :recommend, :Comment)
    end

    def get_average_rating
      @avg = [@rating.rating_1, @rating.rating_2, @rating.rating_3, @rating.rating_4, @rating.rating_5]
      @rating.update_attributes(:total_rating => @avg.instance_eval { reduce(:+) / size.to_f })
    end

    def add_to_overall_rating
      @rate = Rating.find(@rating.id)
      @sr = Rating.where(:stylist_id => @rate.stylist)
      @hstylist = Stylist.find(@rate.stylist.id)
      @arr = @sr.map{|c| c.total_rating}
      @hstylist.update_attributes(:overall_rating => @arr.instance_eval { reduce(:+) / size.to_f })
    end

    def update_overall_rating
      @sr = Rating.where(:stylist_id => @rating.stylist.id)
      @hstylist = Stylist.find(@rating.stylist.id)
      @arr = @sr.map{|c| c.total_rating}
        if @sr.count == 0
          @hstylist.update_attributes(:overall_rating => 0.0)
        else
        @hstylist.update_attributes(:overall_rating => @arr.instance_eval { reduce(:+) / size.to_f })
        end
    end

    def get_tables
      @stylist = Stylist.all
      @client = Client.all
      @style = Style.all
    end

    def resolve_layout
      case action_name
      when 'index', 'show', 'show_admin', 'new', 'create', 'edit', 'update', 'delete', 'destroy'
        'admin'
      when 'show_stylist'
        'application'
      when 'show_client'
        'application'
      end
    end





end

app/helpers/ratings_helper.rb
module RatingsHelper
end

app/views/ratings/_index_ratings.html.erb
<table>
  <tr>
    <th>Rating ID:</th>
    <td><%= rating.id %></td>
  </tr>
  <tr>
    <th>Stylist:</th>
    <td><%= Stylist.find(rating.stylist_id).username %></td>
  </tr>
  <tr>
    <th>Client:</th>
    <td><%= Client.find(rating.client_id).username  %></td>
  </tr>
  <tr>
    <th>Date of Appointment:</th>
    <td><%= rating.date_of_appointment.strftime("%d %B %Y") %></td>
  </tr>
  <tr>
    <th>Total Rating</th>
    <td><%= rating.total_rating %></td>
  </tr>
  <tr>
    <th>Will you return?</th>
    <td><%= rating.return ? "Yes" : "No" %></td>
  </tr>
  <tr>
    <th>Will you recommend?</th>
    <td><%= rating.recommend ? "Yes" : "No" %></td>
  </tr>

</table>

app/views/ratings/_index_stylist_ratings.html.erb
<div class = "media w-5">

  <div>
    <%= image_tag rating.client.picture.url(:thumb).to_s, class: " d-flex align-self-center img-fluid w-50" %>
  </div>

<div class = "media-body  ">
      <h6><%= rating.client.username.capitalize %>'s Review:</h5>
      <p><span class = "badge badge-primary badge-pill bg-warning " style = "color:black"><%= rating.total_rating %>/5.0</span></p>
      <p>Value: <%= rating.rating_1 %> / Venue: <%= rating.rating_2 %> / Needs Met: <%= rating.rating_3 %> / Professional: <%= rating.rating_4 %>/ Gentle: <%= rating.rating_5 %></p>
      <p><strong>Will you return?: </strong><%= rating.return? ? "Yes" : "No" %>  |
     <strong>Will you recommend?: </strong><%= rating.recommend? ? "Yes" : "No" %></p>
</div>

</div>

app/views/ratings/_ratings_form.erb
<%= f.hidden_field(:stylist_id) %>
<%= f.hidden_field(:client_id) %>
<%  %>

<div class = 'p-3' style = 'background-color:black; color:white; border-radius:5px; text-align:center;'>
    <h5> <%=  %>Review Form</h5>
</div>

<div class = "register_form p-3">
    <fieldset>
      <div class ='row form-group'>
        <label class = 'form-control-label col-md-4 text-center'>Date of Your Appointment:</label>
        <%= f.date_select :date_of_appointment , class: 'form-control col-md-8 text-center' %>
      </div>
<hr>

      <div class ='row form-group'>
        <label class = 'radio-inline col-md-4 text-center'>I got value for my money:</label>
        <div class = 'col-md-8'>
          <%= f.radio_button :rating_1, 1, type: 'radio', class: "m-3" %><span>1</span>
          <%= f.radio_button :rating_1, 2, type: 'radio', class: "m-3"%><span>2</span>
          <%= f.radio_button :rating_1, 3, type: 'radio', class: "m-3"%><span>3</span>
          <%= f.radio_button :rating_1, 4, type: 'radio', class: "m-3"%><span>4</span>
          <%= f.radio_button :rating_1, 5, type: 'radio', class: "m-3"%><span>5</span>
        </div>
      </div>
<hr>
      <div class ='row form-group'>
        <label class = 'radio-inline col-md-4 text-center'>The venue was clean and hygienic:</label>
        <div class = 'col-md-8'>
          <%= f.radio_button :rating_2, 1, type: 'radio', class: "m-3" %><span>1</span>
          <%= f.radio_button :rating_2, 2, type: 'radio', class: "m-3"%><span>2</span>
          <%= f.radio_button :rating_2, 3, type: 'radio', class: "m-3"%><span>3</span>
          <%= f.radio_button :rating_2, 4, type: 'radio', class: "m-3"%><span>4</span>
          <%= f.radio_button :rating_2, 5, type: 'radio', class: "m-3"%><span>5</span>
        </div>
      </div>
<hr>
      <div class ='row form-group'>
        <label class = 'radio-inline col-md-4 text-center'>My needs and expectation were met:</label>
        <div class = 'col-md-8'>
          <%= f.radio_button :rating_3, 1, type: 'radio', class: "m-3" %><span>1</span>
          <%= f.radio_button :rating_3, 2, type: 'radio', class: "m-3"%><span>2</span>
          <%= f.radio_button :rating_3, 3, type: 'radio', class: "m-3"%><span>3</span>
          <%= f.radio_button :rating_3, 4, type: 'radio', class: "m-3"%><span>4</span>
          <%= f.radio_button :rating_3, 5, type: 'radio', class: "m-3"%><span>5</span>
        </div>
      </div>
<hr>
      <div class ='row form-group'>
        <label class = 'radio-inline col-md-4 text-center'>Acted in a professional manner:</label>
        <div class = 'col-md-8'>
          <%= f.radio_button :rating_4, 1, type: 'radio', class: "m-3" %><span>1</span>
          <%= f.radio_button :rating_4, 2, type: 'radio', class: "m-3"%><span>2</span>
          <%= f.radio_button :rating_4, 3, type: 'radio', class: "m-3"%><span>3</span>
          <%= f.radio_button :rating_4, 4, type: 'radio', class: "m-3"%><span>4</span>
          <%= f.radio_button :rating_4, 5, type: 'radio', class: "m-3"%><span>5</span>
        </div>
      </div>
<hr>
      <div class ='row form-group'>
        <label class = 'radio-inline col-md-4 text-center'>Was gentle when handling my hair:</label>
        <div class = 'col-md-8'>
          <%= f.radio_button :rating_5, 1, type: 'radio', class: "m-3" %><span>1</span>
          <%= f.radio_button :rating_5, 2, type: 'radio', class: "m-3"%><span>2</span>
          <%= f.radio_button :rating_5, 3, type: 'radio', class: "m-3"%><span>3</span>
          <%= f.radio_button :rating_5, 4, type: 'radio', class: "m-3"%><span>4</span>
          <%= f.radio_button :rating_5, 5, type: 'radio', class: "m-3"%><span>5</span>
        </div>
      </div>
<hr>
      <div class ='row form-group'>
          <label class = 'checkbox-inline col-md-4 text-center'>Will you returning?</label>
        <div class = 'col-md-8'>
            <%= f.radio_button :return, 1, type: "checkbox", class: "m-3" %>Yes
            <%= f.radio_button :return, 0, type: "checkbox", class: "m-3" %>No
        </div>
      </div>
<hr>
      <div class ='row form-group'>
          <label class = 'checkbox-inline col-md-4 text-center'>Would you recommend the Stylist?</label>

          <div class = 'col-md-8'>
            <%= f.radio_button :recommend, 1, type: "checkbox", class: "m-3" %>Yes
            <%= f.radio_button :recommend, 0, type: "checkbox", class: "m-3" %>No
          </div>
      </div>
<hr>
      <div class ='form-group'>
        <label class = 'form-control-label'>Please tell us more about your experience:</label>
        <%= f.text_area :Comment, class: 'form-control' %>
      </div>
    </fieldset>
<hr>
    <div class = 'text-center'>
      <%= f.submit "Submit Rating", class: "btn btn-hl" %>
    </div>

app/views/ratings/_show_rating.html.erb
<div class = 'container'>

<div class = 'row' style = 'margin-top:5px;'>
  <div class = 'col col-md-6 text-center'>
  <% if current_user.has_role? :def_admin %>
    <%= link_to("<< Back Reviews", ratings_path(:admin_id => current_user.id)) %>
  <% elsif current_user.has_role? :def_client %>
    <%= link_to("<< Back to Stylist", stylist_path(@rating.stylist.id, :client_id => current_user.id)) %>
  <% elsif current_user.has_role? :def_stylist %>
    <%= link_to("<< Back to Stylist", stylist_path(@rating.stylist.id, :stylist_id => current_user.id)) %>
  <% end %>
  </div>
  <div class = 'col col-md-6 text-center'>
    <% if (current_user.has_role? :def_client) && (current_user.id == @rating.client.id) %>
      <%= button_to "Edit My Rating", edit_rating_path(@rating), method: :get, class: "btn btn-h1 btn-sm" %>
    <% end %>
  </div>
</div>
<div class = 'text-center'>
  <h2>Review Details</h2>
</div>

  <table class = "table table-hover table-sm text-center">

    <tr>
      <th>Reviewed by:</th>
      <td><%= @client.username %></td>
    </tr>

    <tr>
      <th>Stylist:</th>
      <td><%= @stylist.username %></td>
    </tr>

    <tr>
      <th>Date of Appointment:</th>
      <td><%= @rating.date_of_appointment.strftime("%d %B %Y") %></td>
    </tr>

    <tr>
      <th>I got value for my money:</th>
      <td><%= @rating.rating_1 %>/5.0</td>
    </tr>

    <tr>
      <th>The venue was clean and hygienic:</th>
      <td><%= @rating.rating_2 %>/5.0</td>
    </tr>

    <tr>
      <th>My needs and expectations were met:</th>
      <td><%= @rating.rating_3 %>/5.0</td>
    </tr>

    <tr>
      <th>Acted in a professional manner:</th>
      <td><%= @rating.rating_4 %>/5.0</td>
    </tr>

    <tr>
      <th>Was gentle when handling my hair:</th>
      <td><%= @rating.rating_5 %>/5.0</td>
    </tr>

    <tr>
      <th>Will You Return To <%= @stylist.username %>?: </th>
      <td><%= @rating.return ? 'Yes' : 'No' %></td>
    </tr>

    <tr>
      <th>Would You Recommend <%= @stylist.username %> to a friend?: </th>
      <td><%= @rating.recommend ? 'Yes' : 'No' %></td>
    </tr>

    <tr>
      <th>My Experience with <%= @stylist.username %>:</th>
      <td><%= @rating.Comment %></td>
    </tr>
  </table>

  <div class = 'row'>
    <div class = 'col text-center'>
    <% if current_user.has_role? :def_admin %>
      <%= link_to("Edit", '#') %>,
      <%= link_to("Delete", '#') %>
    <% elsif current_user.id == @client.id %>
    <div class = 'btn-group text-center'>
        <%= button_to "Delete My Rating", delete_rating_path(@rating), method: :get, class: "btn btn-danger btn-sm" %>
    </div>
    <% end %>
      </div>
  </div>

</div>

app/views/ratings/delete.html.erb
<div class = 'container'>

  <div class = 'm-3'>
      <%= link_to("<< Back to Rating", rating_path(@rating, :client_id => @rating.client.id, :stylist_id => @rating.stylist.id )) %>
  </div>

  <div class = 'text-center'>
    <h2>Delete Review</h2>

    <%= form_for(@rating, :method => 'delete') do |f| %>

      <p>Are you sure you want to permanently delete this review?</p>



      <div class="form-buttons">
        <%= f.submit("Delete Rating", class: 'btn btn-danger btn-sm') %>
      </div>

    <% end %>
  </div>

</div>

app/views/ratings/edit.html.erb
<div class = "container">

  <div>
    <%= link_to("<< Back to Stylist", stylist_path(@stylist)) %>
  </div>


  <div>

  <%= form_for(@rating) do |f| %>

    <%= error_messages_for(f.object) %>

   <%= render(:partial => 'ratings_form', :locals => {:f => f}) %>

    <% end %>
  </div>
</div>

app/views/ratings/index.html.erb
<div class = 'container'>
  <h2>Reviews</h2>

<div class = 'card-group'>

  <% @rating.each do |rating| %>
    <div class = 'stylist-list'>
      <div class = 'card text-center'>

        <div class = 'card-body'>
            <%= render(:partial => 'index_ratings', :html => {:multiport => true}, :locals => {:rating => rating})%>
        </div><!-- card-body -->

        <div class = 'card-footer'>
          <%= link_to("View Review", rating_path(rating))%>
        </div><!-- card-footer -->
        
    </div><!-- card -->

    </div><!-- stylist-list -->
  <% end %>
</div> <!-- card-group -->

</div>

app/views/ratings/new.html.erb
<div class = "container">

  <%= link_to("<< Back to Stylist", stylist_path(@stylist)) %>

    <div>
      <%= form_for(@rating) do |f| %>

        <%= error_messages_for(f.object) %>

        <form>
          <%= render(:partial => 'ratings_form', :locals => {:f => f}) %>

        </form>

      <% end %>
    </div>

</div>

app/views/ratings/show.html.erb
<%= render(:partial => 'show_rating', :hmtl => {:multiport => true}, :locals => {:rating => @rating}) %>