config/routes.rb
Rails.application.routes.draw do

  root 'home#index'
  #root 'home#construction'
  #get 'home', :to => 'home#index'
  get 'stylist_home/index'

  get 'alog', :to => 'admin_access#menu'
  get 'admin_access/login'
  get 'admin_access/menu'
  post 'admin_access/attempt_login'
  get 'admin_access/logout'


  get 'client_access/login'
  get 'client_access/menu'
  post 'client_access/attempt_login'
  get 'client_access/logout'
  get 'client_access/forgot'
  post 'client_access/reset'
  get 'client_access/password_form'
  post 'client_access/update_password'


  get 'stylist_access/stylist_login'
  get 'stylist_access/stylist_menu'
  post 'stylist_access/stylist_attempt_login'
  get 'stylist_access/stylist_logout'
  get 'stylist_access/forgot'
  post 'stylist_access/reset'
  get 'stylist_access/password_form'
  post 'stylist_access/update_password'

    resources :stylists do
        member do
          get :delete
          get :new_stylist_rating
          post :create_stylist_rating
          get :new_portfolio
          post :create_portfolio
          get :edit_offering
          patch :update_offering
        end
      end

      resources :clients do
        member do
          get :delete
          get :show_style
          post :create_fav_styles
          delete :destroy_fav_styles
          post :create_fav_stylists
          delete :destroy_fav_stylists
        end

        collection do
          get :index_styles
        end
      end

      resources :ratings do
        member do
          get :delete
          get :show_admin
        end
      end

      resources :styles do
        member do
          get :delete
        end
      end

      resources :portfolios do
        member do
          get :delete
          get :show_client
          get :show_stylist
          get :show_admin
        end
      end

      resources :admins do
        member do
          get :delete
          get :show_rating
          get :edit_rating
          patch :update_rating
          get :delete_rating
          delete :destroy_rating
          get :show_portfolio
          get :edit_portfolio
          patch :update_portfolio
          get :delete_portfolio
          delete :destroy_portfolio

        end
        collection do
          get :index_ratings
          get :index_portfolios
        end
      end


      resources :hairstyles do
        member do
          get :delete
        end
      end

      resources :hairstyle_offerings do
        member do
          get :delete
        end
      end

      resources :hairstyle_requests do
        member do
          get :delete
        end
      end

      resources :hairstyle_matches do
        member do
          get :delete
        end
      end



      resources :cities do
          member do
            get :delete
          end

          collection do
            post :create_all
          end
        end


      resources :areas do
        member do
          get :delete
        end

        collection do
          get :remove_all
        end
      end

      resources :contact_forms do
        member do
          get :delete
        end
      end

      resources :blogs do
        member do
          get :delete
        end
      end

      resources :conversations, only: [:index, :show]
      resources :personal_messages, only: [:new, :create]
      resources :users, only: [:index]

      resources :requests
      resources :responses

end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

app/models/style.rb
class Style < ApplicationRecord

  mount_uploader :image, ImageUploader
  has_and_belongs_to_many :clients, :join_table => "fav_styles"



end

app/controllers/styles_controller.rb
class StylesController < ApplicationController

  layout "application"

  before_action :get_stylists_and_clients, :only => [:new, :create, :edit, :update]


  def index
    @style = Style.all
  end

  def show
    @style = Style.find(params[:id])
  end

  def new
    @service = Service.all
    @style = Style.new
  end

  def create
    @service = Service.all
      @style = Style.create(style_params)

        if @style.save
          redirect_to(style_path(@style))
        else
          render 'new'
        end

  end

  def edit
    @service = Service.all
    @style = Style.find(params[:id])
  end

  def update
    @service = Service.all
    @style = Style.find(params[:id])

      if @style.update_attributes(style_params)
        redirect_to(style_path(@style))
      else
        render ('edit')
      end

  end

  def delete
      @style = Style.find(params[:id])
  end

  def destroy
    @style = Style.find(params[:id])
    @style.destroy
    redirect_to (styles_path)
  end

  private

  def style_params
    params.require(:style).permit(:image, :style_name, :service_id, :details, :stylist_id, :client_id, :popularity)
  end

  def get_stylists_and_clients
    @stylist = Stylist.all
    @client = Client.all
  end






end

app/helpers/styles_helper.rb
module StylesHelper
end

app/views/styles/_index_styles.html.erb
<div><%= image_tag style.image.url(:thumb).to_s %></div>

<table>
  <tr>
    <th>Hairstyle:</th>
    <td><%= style.style_name %></td>
  </tr>

</table>

app/views/styles/_show_style.html.erb
<div class = "media">

<%= image_tag @style.image.url(:display).to_s, class: "d-flex align-self-center img-fluid w-25 rounded mr-3" %>

  <div class = "media-body">
    <table>
      <tr>
        <th>Hairstyle:</th>
        <td><%= @style.style_name %></td>
      </tr>

      <tr>
        <th>Details:</th>
        <td><%= @style.details %></td>
      </tr>

      <tr>
        <th>Likes:</th>
        <td><%= @style.clients.count %></td>
      </tr>
    </table>
  </div><!--media-body-->
</div><!--media-->

app/views/styles/_style_form.html.erb
<table>

  <tr>
    <th>Style Picture</th>
    <td><%= s.file_field(:image) %></td>
  </tr>

  <tr>
    <th>Hairstyle</th>
    <td><%= s.select(:service_id, @service.map{|h| [h.name, h.id]}) %></td>
  </tr>

  <tr>
    <th>Details</th>
    <td><%= s.text_area(:details, :size => "50x5") %></td>
  </tr>

</table>

app/views/styles/delete.html.erb
<%= link_to("<< Back to Style", style_path(@style)) %>

<div>
  <h2>Delete Hairstyle</h2>

  <%= form_for(@style, :method => 'delete') do |f| %>

    <p>Are you sure you want to permanently delete this hairstyle?</p>



    <div class="form-buttons">
      <%= f.submit("Delete Hairstyle") %>
    </div>

  <% end %>
</div>

app/views/styles/edit.html.erb
<%= link_to("<< Back to Style", style_path(@style)) %>

<div>
  <h2>Update a Hairstyle</h2>

  <%= form_for(@style) do |s| %>

    <%= render(:partial => 'style_form', :locals => {:s => s}) %>


    <div>
      <%= s.submit("Update Style") %>
    </div>

  <% end %>
</div>

app/views/styles/index.html.erb
<h2> Hairlinkd Gallery </h2>

<%= link_to("Add Hairstyle to Gallery", new_style_path)%>


<% @style.each do |style| %>
  <%= render(:partial => 'index_styles', :html => {:multiport => true}, :locals => {:style => style}) %>
<% end %>

app/views/styles/new.html.erb
<%= link_to("<< Back to Styles", styles_path) %>

<div>
  <h2>Add a Hairstyle</h2>

  <%= form_for(@style) do |s| %>

    <%= render(:partial => 'style_form', :locals => {:s => s}) %>


    <div>
      <%= s.submit("Add Style") %>
    </div>

  <% end %>
</div>

app/views/styles/show.html.erb
<%= link_to("<< Back to Hairstyles", styles_path) %>

<div>
  <h2>Details of Hairstyles</h2>
</div>

<div>
  <%= link_to("Edit", edit_style_path(@style))%>,
  <%= link_to("Delete", delete_style_path(@style))%><br /><br />
</div>

<div>
  <%= render(:partial => "show_style", :html => {:multiport => true}, :locals => {:style => @style})%>
</div>

  <%= link_to("Like", '#', :method => :post )%>